const number1 = 3;
const number2 = 4;
const product = (number1 * number2);
console.log('The value of product is:', product);
console.log('The typeof product is:', typeof product);
const charge = 33;
const payment = 18;
const amountRemaining = (charge - payment);
console.log('The value of amountRemaining is:', amountRemaining);
console.log('The typeof amountRemaining is:', typeof amountRemaining);
const tests = 90;
const assignments = 70;
const final = 80;
const grade = ((tests + assignments + final) / 3);
console.log('The value of grade is:', grade);
console.log('They typeof grade is:', typeof grade);
const firstName = 'Bryan ';
const lastName = 'Amora';
const fullName = (firstName + lastName);
console.log('The value of fullName is:', fullName);
console.log('The typeof fullName is:', typeof fullName);
const pH = 6;
const isAcidic = (pH < 7);
console.log('The value of isAcidic is:', isAcidic);
console.log('The typeof isAcidic is:', typeof isAcidic);
const numberOfSoldiers = 690;
const isSparta = (numberOfSoldiers === 300);
console.log('The value of isSparta is:', isSparta);
console.log('The typeof isSparta is:', typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT!';
console.log('The value of nickname is:', nickname);
console.log('The typeof nickname is:', typeof nickname);
